// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/config_service.proto

package config_service

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Ensure timestamppb is used
var _ = timestamppb.Now

type Environment int32

const (
	Environment_ENV_UNSPECIFIED Environment = 0
	Environment_ENV_DEV         Environment = 1
	Environment_ENV_STAGING     Environment = 2
	Environment_ENV_PROD        Environment = 3
)

func (e Environment) String() string {
	switch e {
	case Environment_ENV_DEV:
		return "ENV_DEV"
	case Environment_ENV_STAGING:
		return "ENV_STAGING"
	case Environment_ENV_PROD:
		return "ENV_PROD"
	default:
		return "ENV_UNSPECIFIED"
	}
}

type ConfigItem struct {
	Key         string                 `json:"key,omitempty"`
	Value       string                 `json:"value,omitempty"`
	Environment Environment            `json:"environment,omitempty"`
	Namespace   string                 `json:"namespace,omitempty"`
	Version     uint64                 `json:"version,omitempty"`
	CreatedAt   *timestamppb.Timestamp `json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `json:"updated_at,omitempty"`
	UpdatedBy   string                 `json:"updated_by,omitempty"`
	Comment     string                 `json:"comment,omitempty"`
}

// --- Namespace messages ---

type CreateNamespaceRequest struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}

type CreateNamespaceResponse struct {
	Success bool `json:"success,omitempty"`
}

type ListNamespacesRequest struct{}

type ListNamespacesResponse struct {
	Namespaces []string `json:"namespaces,omitempty"`
}

type DeleteNamespaceRequest struct {
	Name string `json:"name,omitempty"`
}

type DeleteNamespaceResponse struct {
	Success bool `json:"success,omitempty"`
}

// --- Config CRUD messages ---

type GetConfigRequest struct {
	Namespace   string      `json:"namespace,omitempty"`
	Environment Environment `json:"environment,omitempty"`
	Key         string      `json:"key,omitempty"`
	Version     uint64      `json:"version,omitempty"`
}

type GetConfigResponse struct {
	Item *ConfigItem `json:"item,omitempty"`
}

type PutConfigRequest struct {
	Namespace   string      `json:"namespace,omitempty"`
	Environment Environment `json:"environment,omitempty"`
	Key         string      `json:"key,omitempty"`
	Value       string      `json:"value,omitempty"`
	UpdatedBy   string      `json:"updated_by,omitempty"`
	Comment     string      `json:"comment,omitempty"`
}

type PutConfigResponse struct {
	Version uint64 `json:"version,omitempty"`
}

type DeleteConfigRequest struct {
	Namespace   string      `json:"namespace,omitempty"`
	Environment Environment `json:"environment,omitempty"`
	Key         string      `json:"key,omitempty"`
	Comment     string      `json:"comment,omitempty"`
}

type DeleteConfigResponse struct {
	Success bool `json:"success,omitempty"`
}

type ListConfigsRequest struct {
	Namespace   string      `json:"namespace,omitempty"`
	Environment Environment `json:"environment,omitempty"`
	Prefix      string      `json:"prefix,omitempty"`
	Limit       int32       `json:"limit,omitempty"`
	PageToken   string      `json:"page_token,omitempty"`
}

type ListConfigsResponse struct {
	Items         []*ConfigItem `json:"items,omitempty"`
	NextPageToken string        `json:"next_page_token,omitempty"`
}

// --- Version messages ---

type GetConfigVersionRequest struct {
	Namespace   string      `json:"namespace,omitempty"`
	Environment Environment `json:"environment,omitempty"`
	Key         string      `json:"key,omitempty"`
	Version     uint64      `json:"version,omitempty"`
}

type GetConfigVersionResponse struct {
	Item *ConfigItem `json:"item,omitempty"`
}

type ListConfigVersionsRequest struct {
	Namespace   string      `json:"namespace,omitempty"`
	Environment Environment `json:"environment,omitempty"`
	Key         string      `json:"key,omitempty"`
	Limit       int32       `json:"limit,omitempty"`
}

type ListConfigVersionsResponse struct {
	Versions []*ConfigItem `json:"versions,omitempty"`
}

type RollbackConfigRequest struct {
	Namespace     string      `json:"namespace,omitempty"`
	Environment   Environment `json:"environment,omitempty"`
	Key           string      `json:"key,omitempty"`
	TargetVersion uint64      `json:"target_version,omitempty"`
	UpdatedBy     string      `json:"updated_by,omitempty"`
}

type RollbackConfigResponse struct {
	NewVersion uint64 `json:"new_version,omitempty"`
}

// --- Watch messages ---

type WatchConfigRequest struct {
	Namespace   string      `json:"namespace,omitempty"`
	Environment Environment `json:"environment,omitempty"`
	Key         string      `json:"key,omitempty"`
}

type WatchConfigResponse struct {
	Item      *ConfigItem `json:"item,omitempty"`
	EventType string      `json:"event_type,omitempty"`
}

// --- Cluster messages ---

type ClusterStatusRequest struct{}

type ClusterStatusResponse struct {
	LeaderId      string      `json:"leader_id,omitempty"`
	LeaderAddress string      `json:"leader_address,omitempty"`
	Nodes         []*NodeInfo `json:"nodes,omitempty"`
}

type NodeInfo struct {
	Id      string `json:"id,omitempty"`
	Address string `json:"address,omitempty"`
	State   string `json:"state,omitempty"`
}

// ConfigServiceClient is the client API for ConfigService service.
type ConfigServiceClient interface {
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	PutConfig(ctx context.Context, in *PutConfigRequest, opts ...grpc.CallOption) (*PutConfigResponse, error)
	DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
	ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error)
	GetConfigVersion(ctx context.Context, in *GetConfigVersionRequest, opts ...grpc.CallOption) (*GetConfigVersionResponse, error)
	ListConfigVersions(ctx context.Context, in *ListConfigVersionsRequest, opts ...grpc.CallOption) (*ListConfigVersionsResponse, error)
	RollbackConfig(ctx context.Context, in *RollbackConfigRequest, opts ...grpc.CallOption) (*RollbackConfigResponse, error)
	WatchConfig(ctx context.Context, in *WatchConfigRequest, opts ...grpc.CallOption) (ConfigService_WatchConfigClient, error)
	ClusterStatus(ctx context.Context, in *ClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/CreateNamespace", in, out, opts...)
	return out, err
}

func (c *configServiceClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/ListNamespaces", in, out, opts...)
	return out, err
}

func (c *configServiceClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error) {
	out := new(DeleteNamespaceResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/DeleteNamespace", in, out, opts...)
	return out, err
}

func (c *configServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/GetConfig", in, out, opts...)
	return out, err
}

func (c *configServiceClient) PutConfig(ctx context.Context, in *PutConfigRequest, opts ...grpc.CallOption) (*PutConfigResponse, error) {
	out := new(PutConfigResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/PutConfig", in, out, opts...)
	return out, err
}

func (c *configServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	out := new(DeleteConfigResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/DeleteConfig", in, out, opts...)
	return out, err
}

func (c *configServiceClient) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error) {
	out := new(ListConfigsResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/ListConfigs", in, out, opts...)
	return out, err
}

func (c *configServiceClient) GetConfigVersion(ctx context.Context, in *GetConfigVersionRequest, opts ...grpc.CallOption) (*GetConfigVersionResponse, error) {
	out := new(GetConfigVersionResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/GetConfigVersion", in, out, opts...)
	return out, err
}

func (c *configServiceClient) ListConfigVersions(ctx context.Context, in *ListConfigVersionsRequest, opts ...grpc.CallOption) (*ListConfigVersionsResponse, error) {
	out := new(ListConfigVersionsResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/ListConfigVersions", in, out, opts...)
	return out, err
}

func (c *configServiceClient) RollbackConfig(ctx context.Context, in *RollbackConfigRequest, opts ...grpc.CallOption) (*RollbackConfigResponse, error) {
	out := new(RollbackConfigResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/RollbackConfig", in, out, opts...)
	return out, err
}

type ConfigService_WatchConfigClient interface {
	Recv() (*WatchConfigResponse, error)
	grpc.ClientStream
}

type configServiceWatchConfigClient struct {
	grpc.ClientStream
}

func (x *configServiceWatchConfigClient) Recv() (*WatchConfigResponse, error) {
	m := new(WatchConfigResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configServiceClient) WatchConfig(ctx context.Context, in *WatchConfigRequest, opts ...grpc.CallOption) (ConfigService_WatchConfigClient, error) {
	stream, err := c.cc.NewStream(ctx, &ConfigService_ServiceDesc.Streams[0], "/config_service.ConfigService/WatchConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &configServiceWatchConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

func (c *configServiceClient) ClusterStatus(ctx context.Context, in *ClusterStatusRequest, opts ...grpc.CallOption) (*ClusterStatusResponse, error) {
	out := new(ClusterStatusResponse)
	err := c.cc.Invoke(ctx, "/config_service.ConfigService/ClusterStatus", in, out, opts...)
	return out, err
}

// ConfigServiceServer is the server API for ConfigService service.
type ConfigServiceServer interface {
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	PutConfig(context.Context, *PutConfigRequest) (*PutConfigResponse, error)
	DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
	GetConfigVersion(context.Context, *GetConfigVersionRequest) (*GetConfigVersionResponse, error)
	ListConfigVersions(context.Context, *ListConfigVersionsRequest) (*ListConfigVersionsResponse, error)
	RollbackConfig(context.Context, *RollbackConfigRequest) (*RollbackConfigResponse, error)
	WatchConfig(*WatchConfigRequest, ConfigService_WatchConfigServer) error
	ClusterStatus(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error)
}

type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (UnimplementedConfigServiceServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedConfigServiceServer) DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (UnimplementedConfigServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedConfigServiceServer) PutConfig(context.Context, *PutConfigRequest) (*PutConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutConfig not implemented")
}
func (UnimplementedConfigServiceServer) DeleteConfig(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedConfigServiceServer) ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigs not implemented")
}
func (UnimplementedConfigServiceServer) GetConfigVersion(context.Context, *GetConfigVersionRequest) (*GetConfigVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigVersion not implemented")
}
func (UnimplementedConfigServiceServer) ListConfigVersions(context.Context, *ListConfigVersionsRequest) (*ListConfigVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigVersions not implemented")
}
func (UnimplementedConfigServiceServer) RollbackConfig(context.Context, *RollbackConfigRequest) (*RollbackConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackConfig not implemented")
}
func (UnimplementedConfigServiceServer) WatchConfig(*WatchConfigRequest, ConfigService_WatchConfigServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchConfig not implemented")
}
func (UnimplementedConfigServiceServer) ClusterStatus(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterStatus not implemented")
}

type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

type ConfigService_WatchConfigServer interface {
	Send(*WatchConfigResponse) error
	grpc.ServerStream
}

type configServiceWatchConfigServer struct {
	grpc.ServerStream
}

func (x *configServiceWatchConfigServer) Send(m *WatchConfigResponse) error {
	return x.ServerStream.SendMsg(m)
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/CreateNamespace"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/ListNamespaces"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/DeleteNamespace"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/GetConfig"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_PutConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).PutConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/PutConfig"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).PutConfig(ctx, req.(*PutConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/DeleteConfig"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteConfig(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/ListConfigs"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListConfigs(ctx, req.(*ListConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetConfigVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetConfigVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/GetConfigVersion"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetConfigVersion(ctx, req.(*GetConfigVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListConfigVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListConfigVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/ListConfigVersions"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListConfigVersions(ctx, req.(*ListConfigVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_RollbackConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).RollbackConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/RollbackConfig"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).RollbackConfig(ctx, req.(*RollbackConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_WatchConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigServiceServer).WatchConfig(m, &configServiceWatchConfigServer{stream})
}

func _ConfigService_ClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/config_service.ConfigService/ClusterStatus"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ClusterStatus(ctx, req.(*ClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config_service.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreateNamespace", Handler: _ConfigService_CreateNamespace_Handler},
		{MethodName: "ListNamespaces", Handler: _ConfigService_ListNamespaces_Handler},
		{MethodName: "DeleteNamespace", Handler: _ConfigService_DeleteNamespace_Handler},
		{MethodName: "GetConfig", Handler: _ConfigService_GetConfig_Handler},
		{MethodName: "PutConfig", Handler: _ConfigService_PutConfig_Handler},
		{MethodName: "DeleteConfig", Handler: _ConfigService_DeleteConfig_Handler},
		{MethodName: "ListConfigs", Handler: _ConfigService_ListConfigs_Handler},
		{MethodName: "GetConfigVersion", Handler: _ConfigService_GetConfigVersion_Handler},
		{MethodName: "ListConfigVersions", Handler: _ConfigService_ListConfigVersions_Handler},
		{MethodName: "RollbackConfig", Handler: _ConfigService_RollbackConfig_Handler},
		{MethodName: "ClusterStatus", Handler: _ConfigService_ClusterStatus_Handler},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfig",
			Handler:       _ConfigService_WatchConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/config_service.proto",
}
